runtime: python312

handlers:
- url: /
  static_files: index.html
  upload: index\.html

- url: /(.+)
  static_files: \1
  upload: .+

error_handlers:
- error_code: not_found
  file: 404.html

default_expiration: "1d"
